# Generated by Django 6.0.3 on 2026-03-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategoriya (ixtiyoriy)')),
                ('keyword', models.CharField(help_text="User xabarida shu so'z qatnashsa, javob qaytariladi", max_length=255, verbose_name="Kalit so'z yoki termin")),
                ('answer', models.TextField(verbose_name='Bot qaytaradigan javob')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot bilimi',
                'verbose_name_plural': 'Bot bilimlari',
            },
        ),
    ]
