"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1=(osdoc3n71h664o)8x!x^2zqkxdr&^u969ziwl7(q456-ur1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'files',
    'elementar',
    'adaptive',
    'neural',
    'quiz',
    'practical',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# settings.py
# settings.py

LOGIN_URL = 'login'  # URL nomini (name='login') yozing
LOGIN_REDIRECT_URL = 'core:home'  # URL nomini yoki to'liq yo'lni ('/') yozishingiz mumkin
LOGOUT_REDIRECT_URL = 'core:login' # Chiqqandan keyin yana login sahifasiga qaytarish
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Faylning eng oxiriga statik fayllar uchun sozlamalarni qo'shing
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] # Agar umumiy static papka ishlatsangiz
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "ILMS Platform",
    "SITE_HEADER": "ILMS Admin Panel",
    "SITE_SYMBOL": "psychology",  # Neyrotarmoq ruhidagi tepadagi ikonka
    "SHOW_HISTORY": True,
    "COLORS": {
        "primary": {
            "50": "239, 246, 255",
            "100": "219, 234, 254",
            "200": "191, 219, 254",
            "300": "147, 197, 253",
            "400": "96, 165, 250",
            "500": "99, 102, 241", # Indigo (Neural Path uchun binafsha-ko'k rang)
            "600": "79, 70, 229",
            "700": "67, 56, 202",
            "800": "55, 48, 163",
            "900": "49, 46, 129",
            "950": "30, 27, 75",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False, # Standart ro'yxatni yashirish
        "navigation": [
            {
                "title": _("Fayllar Tizimi"),
                "separator": True,
                "collapsible": True, # Dropdown rejim
                "items": [
                    {
                        "title": _("Dars Papkalari"),
                        "icon": "folder",
                        "link": reverse_lazy("admin:files_folder_changelist"),
                    },
                    {
                        "title": _("Materiallar"),
                        "icon": "attachment",
                        "link": reverse_lazy("admin:files_material_changelist"),
                    },
                    {
                        "title": _("Yuborilgan Fayllar"),
                        "icon": "assignment_returned",
                        "link": reverse_lazy("admin:files_submission_changelist"),
                    },
                ],
            },
            {
                "title": _("Elementar Modul"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Kurslar"),
                        "icon": "school",
                        "link": reverse_lazy("admin:elementar_lesson_changelist"),
                    },
                    {
                        "title": _("Modullar"),
                        "icon": "view_module",
                        "link": reverse_lazy("admin:elementar_module_changelist"),
                    },
                    {
                        "title": _("Darslar"),
                        "icon": "segment",
                        "link": reverse_lazy("admin:elementar_element_changelist"),
                    },
                    {
                        "title": _("Progresslar"),
                        "icon": "analytics",
                        "link": reverse_lazy("admin:elementar_userprogress_changelist"),
                    },
                ],
            },
            {
                "title": _("Adaptive Modul"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Adaptive Modul"),
                        "icon": "lock_open",
                        "link": reverse_lazy("admin:adaptive_course_changelist"),
                    },
                    {
                        "title": _("Kurs Modullari"),
                        "icon": "dashboard_customize",
                        "link": reverse_lazy("admin:adaptive_module_changelist"),
                    },
                    {
                        "title": _("Dars Bosqichlari"),
                        "icon": "format_list_numbered",
                        "link": reverse_lazy("admin:adaptive_element_changelist"),
                    },
                    {
                        "title": _("Progress Tarixi"),
                        "icon": "history_edu",
                        "link": reverse_lazy("admin:adaptive_progress_changelist"),
                    },
                ],
            },
            {
                "title": _("Neyrotarmoq Modul"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Darslar"),
                        "icon": "hub", # Neyrotarmoq tugunlari ramzi
                        "link": reverse_lazy("admin:neural_aipath_changelist"),
                    },
                    {
                        "title": _("Modullar"),
                        "icon": "account_tree",
                        "link": reverse_lazy("admin:neural_module_changelist"),
                    },
                    {
                        "title": _("Dars Elementlari"),
                        "icon": "psychology",
                        "link": reverse_lazy("admin:neural_element_changelist"),
                    },
                    {
                        "title": _("Testlar"),
                        "icon": "quiz",
                        "link": reverse_lazy("admin:neural_quiz_changelist"),
                    },
                    {
                        "title": _("Neyro Progress"),
                        "icon": "data_thresholding",
                        "link": reverse_lazy("admin:neural_neuralprogress_changelist"),
                    },
                ],
            },
            {
                "title": _("Test Tizimi (Markaz)"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Fanlar"),
                        "icon": "library_books",
                        "link": reverse_lazy("admin:quiz_subject_changelist"),
                    },
                    {
                        "title": _("Test Savollari"),
                        "icon": "fact_check",
                        "link": reverse_lazy("admin:quiz_question_changelist"),
                    },
                    {
                        "title": _("Imtihon Seanslari"),
                        "icon": "history",
                        "link": reverse_lazy("admin:quiz_examsession_changelist"),
                    },
                ],
            },
            {
                "title": _("Chatbot & AI Sozlamalari"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Bot Bilimlari"),
                        "icon": "smart_toy", # Robot ikonka
                        "link": reverse_lazy("admin:core_botknowledge_changelist"),
                    },
                ],
            },
            {
                "title": _("Amaliy & Mustaqil"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": _("Topshiriqlar"), "icon": "assignment", "link": reverse_lazy("admin:practical_assignment_changelist")},
                    {"title": _("Talabalar Javoblari"), "icon": "fact_check", "link": reverse_lazy("admin:practical_submission_changelist")},
                ],
            },
            {
                "title": _("Foydalanuvchilar va Guruhlar"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Foydalanuvchilar"),
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Guruhlar"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}
