# Generated by Django 6.0.3 on 2026-03-22 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'Foydalanuvchi progressi', 'verbose_name_plural': 'Foydalanuvchilar progressi'},
        ),
        migrations.AlterField(
            model_name='element',
            name='content',
            field=models.TextField(help_text="Dars matni (HTML bo'lishi mumkin)", verbose_name='Nazariya'),
        ),
        migrations.AlterField(
            model_name='element',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='elementar.module', verbose_name='Modul'),
        ),
        migrations.AlterField(
            model_name='element',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='element',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Mavzu nomi'),
        ),
        migrations.AlterField(
            model_name='element',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video linki', null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Dars nomi'),
        ),
        migrations.AlterField(
            model_name='module',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='elementar.lesson', verbose_name='Dars'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Modul nomi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(choices=[(1, '1-variant'), (2, '2-variant'), (3, '3-variant'), (4, '4-variant')], verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='question',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='elementar.element', verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(max_length=255, verbose_name='Variant 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(max_length=255, verbose_name='Variant 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(max_length=255, verbose_name='Variant 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(max_length=255, verbose_name='Variant 4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Savol matni'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elementar.element', verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Tugatildi'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Talaba'),
        ),
    ]
