# Generated by Django 6.0.3 on 2026-03-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elementar', '0002_alter_userprogress_options_alter_element_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='score',
            field=models.FloatField(default=0, verbose_name="To'plangan ball (%)"),
        ),
    ]
