# Generated by Django 6.0.3 on 2026-03-22 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Dars elementi', 'verbose_name_plural': 'Dars elementlari'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Modul', 'verbose_name_plural': 'Modullar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order'], 'verbose_name': 'Mavzu', 'verbose_name_plural': 'Mavzular'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': 'Foydalanuvchi progressi', 'verbose_name_plural': 'Foydalanuvchilar progressi'},
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='current_level',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='highest_level',
            field=models.IntegerField(default=3, verbose_name='Erishilgan eng yuqori daraja'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Kurs haqida'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='adaptive/courses/', verbose_name='Kurs rasmi'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Kurs nomi'),
        ),
        migrations.AlterField(
            model_name='element',
            name='content',
            field=models.TextField(verbose_name='Dars matni (Nazariya)'),
        ),
        migrations.AlterField(
            model_name='element',
            name='difficulty',
            field=models.IntegerField(choices=[(3, 'Oddiy (3-baholik)'), (4, 'Oʻrta (4-baholik)'), (5, 'Murakkab (5-baholik)')], default=3, verbose_name='Qiyinlik darajasi'),
        ),
        migrations.AlterField(
            model_name='element',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='adaptive.topic', verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='element',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video darslik URL'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='adaptive.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Modul nomi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name="To'g'ri javob raqami"),
        ),
        migrations.AlterField(
            model_name='question',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='adaptive.element', verbose_name='Dars darajasi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(max_length=255, verbose_name='Variant 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(max_length=255, verbose_name='Variant 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(max_length=255, verbose_name='Variant 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(max_length=255, verbose_name='Variant 4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Savol matni'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='adaptive.module', verbose_name='Modul'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Mavzu nomi'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive.element', verbose_name='Oxirgi yopilgan dars'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Mavzu yopildimi?'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='score',
            field=models.FloatField(default=0, verbose_name="To'plangan ball (%)"),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adaptive.topic', verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_progress', to=settings.AUTH_USER_MODEL, verbose_name='Talaba'),
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('topic', 'difficulty')},
        ),
    ]
