# Generated by Django 6.0.3 on 2026-03-14 13:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Topshiriq nomi')),
                ('task_type', models.CharField(choices=[('practical', 'Amaliy mashg’ulot'), ('independent', 'Mustaqil ta’lim')], max_length=20, verbose_name='Turi')),
                ('description', models.TextField(verbose_name='Topshiriq tavsifi')),
                ('file', models.FileField(upload_to='assignments/tasks/', verbose_name='Topshiriq fayli (PDF/Word)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Topshiriq muddati')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/submissions/', verbose_name='Talaba javob fayli')),
                ('comment', models.TextField(blank=True, verbose_name='Talaba izohi')),
                ('grade', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Baho (0-100)')),
                ('teacher_comment', models.TextField(blank=True, verbose_name="O'qituvchi taqrizi")),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='practical.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'user')},
            },
        ),
    ]
